### ISSUE TITLE
change background need to restart nvim for vim-airline take effect

### ISSUE THREAD

**Issue by ForteDexe** [sainnhe/gruvbox-material#121] opened 2022-02-19 21:06 UTC
### Operating system/version

Manjaro KDE

### Terminal emulator/version

kitty

### $TERM environment variable

xterm-kitty

### Feature matrix
```
coc: health#coc#check
========================================================================
  - OK: Environment check passed
  - WARNING: pyx command not work, some extensions may fail to work, checkout ":help |pythonx|"
  - OK: Javascript bundle build/index.js found
  - OK: Service started

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - WARNING: "wilder.nvim" is not registered. (python3 not available)
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - css            ✓ . ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.10 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/bin/python3 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python3.10 does not have the "neovim" module. :help |provider-python|
          python3.9 not found in search path or not executable.
          python3.8 not found in search path or not executable.
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v16.13.2
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `coc`
  - INFO: No healthcheck provided

## Telescope Extension: `file_browser`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/forted/.cache/nvim/lsp.log
  - INFO: Log size: 55 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for comment: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
```

### Minimal vimrc that can reproduce this bug.

```
call plug#begin()
Plug 'sainnhe/gruvbox-material'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

let g:airline_theme='gruvbox_material'
set background=light
colorscheme gruvbox-material

" bind keymap switch bg
function! Switchbg()
	if (&background=='light')
		set background=dark
	else
		set background=light
	endif
endfunction

nnoremap <F12> :call Switchbg()<CR>
```

### Steps to reproduce this bug using minimal vimrc

Launch vim.
Type :set background=dark or white
Or press F12.

### Expected behavior

Change vim-airline to dark/light theme when using the command.

### Actual behavior

vim-airline isnt changing the theme, only hard code to init.vim, then re-open vim.

**Comment by sainnhe** [comment] 2022-02-19 22:29
You need to source /path/to/gruvbox-material/autoload/airline/themes/gruvbox_material.vim

:h autoload

**Comment by ForteDexe** [comment] 2022-02-20 01:01
Sorry I didnt follow, the file "/path/to/gruvbox-material/autoload/airline/themes/gruvbox_material.vim" dont have any function.
<img width="583" alt="image" src="https://user-images.githubusercontent.com/57673412/154824341-7c2f39ad-e9b4-4f9f-8812-3549ef88b466.png">

**Comment by ForteDexe** [comment] 2022-02-20 01:44
Ok, I make it work by add :source to the function of the keymap. But every time it executes, the color of the airline-vim is reverse compare to the background. For example, if the background is dark, then the airline will light.

I have to combine the keymap with this plugin to make it work correctly, but with an extra step, like auto find and replace the setting in init.vim file.
https://github.com/famiu/nvim-reload

**Comment by antoineco** [comment] 2023-04-22 14:38
The key to making this work is to use an autocmd like this one:

- autocmd: https://github.com/antoineco/dotfiles/blob/91d0e4b/nvim/init.lua#L80-L88
    - reload function: https://github.com/antoineco/dotfiles/blob/91d0e4b/nvim/autoload/nviminit/lightline.vim#L7-L15

The example is for lightline, but the same principle applies to airline, you just need to replace the commands.

I also recommended checking https://arslan.io/2021/02/15/automatic-dark-mode-for-terminal-applications/.

Closing because the issue is related to the usage of airline, not of the colorscheme.

**Closed as not planned by antoineco** 2023-04-22 14:38 UTC
Labels: bug
